Task 1 completed
EnigmaVSSUT/Induction-2021 pull request #130
Opened 2021-04-28 15:40 UTC by pooja1306

I felt very good doing so!!

2021-04-28 15:41 UTC, gouravcyber approved these changes

2021-04-30 13:58 UTC, Anubhcv requested changes
Review your task. It doesn't follow the required objectives.

2021-04-30 19:44 UTC, ashuvssut commented
You have done task1 and task2 in single PR. not an issue. but there are still mistakes

Follow what @Anubhcv said. Read tasks carefully. see for yourself what you r missing out🙂

You have done same mistake in both tasks

You have updated your Repo successfully. GG!

2021-05-01 11:25 UTC, ashuvssut approved these changes

2021-05-01 19:17 UTC, merged