photo added
EnigmaVSSUT/Induction-2021 pull request #199
Opened 2021-04-30 15:09 UTC by sa8tyajeet46

task 2 completed

2021-04-30 15:15 UTC, Anubhcv requested changes
Review your task. It doesn't follow the required objectives.

2021-05-01 05:16 UTC, sa8tyajeet46 commented
Bhaiya plz help me I couldn't find the mistake

2021-05-01 05:28 UTC, Anubhcv commented
> Bhaiya plz help me I couldn't find the mistake

You haven't updated your local repo to the upstream repo

2021-05-01 08:13 UTC, Anubhcv approved these changes

2021-05-01 18:55 UTC, merged