task 1 completed
EnigmaVSSUT/Induction-2021 pull request #207
Opened 2021-04-30 16:13 UTC by prativa222

2021-04-30 17:39 UTC, Anubhcv approved these changes

2021-05-01 17:33 UTC, Anubhcv requested changes
Review your task. You have pushed extra files.

2021-05-02 05:48 UTC, prativa222 commented
> Review your task. You have pushed extra files.

bhaiya jo extra files pull hue h use undo kese karu

2021-05-02 09:05 UTC, Anubhcv commented
> > Review your task. You have pushed extra files.
> 
> bhaiya jo extra files pull hue h use undo kese karu

Delete the extra files from your local repo then commit and push.

2021-05-02 12:17 UTC, ashuvssut commented on Open Source/Git1/prativarath.txt
> +200210072
.

2021-05-02 14:40 UTC, prativa222 commented
> > > Review your task. You have pushed extra files.
> > 
> > 
> > bhaiya jo extra files pull hue h use undo kese karu
> 
> Delete the extra files from your local repo then commit and push.

bhaiya pata nhi chal rhi h konsi extra file push hue h or me task 1 submit karchuki hu par meri name show nhi kr rhi h name list me

2021-05-02 14:45 UTC, Anubhcv commented
In git2 folder you have uploaded an extra file. 
Your name will show in name list when we merge this pr after your task 2 gets approved.

2021-05-03 08:42 UTC, Anubhcv approved these changes

2021-05-03 09:19 UTC, prativa222 commented
> In git2 folder you have uploaded an extra file.
> Your name will show in name list when we merge this pr after your task 2 gets approved.

Bhaiya task 2 submit ho gayi na meri ? Pata nhi chal rhi h..

2021-05-03 13:14 UTC, merged