Task 2
EnigmaVSSUT/Induction-2021 pull request #238
Opened 2021-05-01 18:12 UTC by Debabrata47

2021-05-01 18:14 UTC, Anubhcv requested changes
Review your task. It doesn't follow the required objectives.

2021-05-01 18:24 UTC, gouravcyber commented
Your PR still doesn't meet the task objectives.

2021-05-14 17:17 UTC, Anubhcv approved these changes

2021-05-15 16:22 UTC, Debabrata47 commented
Task 2 Web develpment Done

2021-05-15 16:35 UTC, Anubhcv approved these changes

2021-05-16 13:07 UTC, merged