task 3
EnigmaVSSUT/Induction-2021 pull request #273
Opened 2021-05-12 18:32 UTC by kareena18

2021-05-12 19:02 UTC, ankush0939 requested changes
U haven't provided the link of the site. host it and provide the txt file asked

2021-05-12 20:19 UTC, ankush0939 approved these changes

2021-05-15 11:06 UTC, kareena18 commented
web dev task-2 completed

2021-05-15 11:27 UTC, Anubhcv approved these changes

2021-05-16 13:15 UTC, merged