#Task 1 completed!
EnigmaVSSUT/Induction-2021 pull request #287
Opened 2021-05-13 14:45 UTC by harshranjan63

Kindly verify My website!is it ok?

2021-05-13 16:53 UTC, Anubhcv approved these changes

2021-05-14 19:18 UTC, harshranjan63 commented
Task 2 done!
Kindly check out my task 2.

2021-05-15 03:44 UTC, Anubhcv requested changes
Review your task, it doesn't toggle back to default theme after theme is changed.

2021-05-15 06:46 UTC, harshranjan63 commented
Task 2 updated!
Kindly check out my task 2 after updatating.
New URL: https://harshranjan63.github.io/harshranjan3.github.io/

2021-05-15 06:57 UTC, Anubhcv approved these changes

2021-05-16 13:04 UTC, merged