task 3
EnigmaVSSUT/Induction-2021 pull request #290
Opened 2021-05-13 17:07 UTC by hema99s

https://hema99s.github.io/mypage/

2021-05-13 18:24 UTC, chandrasekhar2039 requested changes
well your Task doesn't satisfy the required Objective.

2021-05-14 14:21 UTC, chandrasekhar2039 submitted a review, later dismissed
Remove the submodule and add the original folder, containing your webpage

2021-05-15 11:33 UTC, Anubhcv requested changes
Delete the submodule and rename your uploaded folder to your name.

2021-05-15 15:10 UTC, ankush0939 approved these changes

2021-05-16 13:04 UTC, merged