WebDev Task1 Completed
EnigmaVSSUT/Induction-2021 pull request #294
Opened 2021-05-14 06:59 UTC by Ryuzaki2692

https://ryuzaki2692.github.io/WebDev/

2021-05-14 07:06 UTC, Anubhcv requested changes
Add a screenshot of your webpage.

2021-05-14 08:02 UTC, Ryuzaki2692 commented
Added the screenshot sir

2021-05-14 08:03 UTC, Anubhcv approved these changes

2021-05-15 16:18 UTC, Ryuzaki2692 commented
Task 2 Web Development Assignment Done

2021-05-15 16:29 UTC, Anubhcv approved these changes

2021-05-16 13:02 UTC, merged