Web Page Task1
EnigmaVSSUT/Induction-2021 pull request #297
Opened 2021-05-14 08:48 UTC by swaraj79

2021-05-14 09:47 UTC, Anubhcv requested changes
Add a screenshot of your webpage.

2021-05-14 17:29 UTC, Anubhcv approved these changes

2021-05-16 04:44 UTC, swaraj79 commented
Web page Task-2 Done

2021-05-16 09:56 UTC, Anubhcv approved these changes

2021-05-16 13:00 UTC, merged