web dev task1
EnigmaVSSUT/Induction-2021 pull request #298
Opened 2021-05-14 08:53 UTC by sa8tyajeet46

2021-05-14 09:50 UTC, Anubhcv requested changes
Add a text file containing the url of your webpage.

2021-05-15 01:33 UTC, sa8tyajeet46 commented
> Add a text file containing the url of your webpage.

Done bhaiya

2021-05-15 03:45 UTC, Anubhcv approved these changes

2021-05-15 11:55 UTC, sa8tyajeet46 commented
task2 completed

2021-05-15 12:03 UTC, Anubhcv approved these changes

2021-05-16 13:00 UTC, merged