task 3 submitted
EnigmaVSSUT/Induction-2021 pull request #301
Opened 2021-05-14 11:46 UTC by sourav123608

2021-05-14 13:18 UTC, Anubhcv approved these changes

2021-05-15 13:14 UTC, sourav123608 commented
task 2 web development done

2021-05-15 13:41 UTC, Anubhcv requested changes
Review your task, you haven't uploaded your task 2 files.

2021-05-15 15:19 UTC, sourav123608 commented
I added the files

2021-05-15 15:20 UTC, Anubhcv approved these changes

2021-05-16 12:56 UTC, merged