Web page task1
EnigmaVSSUT/Induction-2021 pull request #302
Opened 2021-05-14 12:12 UTC by Meenakshi143

2021-05-14 13:20 UTC, Anubhcv approved these changes

2021-05-16 08:46 UTC, Meenakshi143 commented
Task 2 completed

2021-05-16 10:05 UTC, Anubhcv requested changes
The url to your task-2 webpage is incorrect, fix it and commit again.

2021-05-16 14:59 UTC, Meenakshi143 commented
page-url updated

2021-05-16 17:06 UTC, Anubhcv approved these changes

2021-05-18 06:45 UTC, merged