Web Page Task 1
EnigmaVSSUT/Induction-2021 pull request #303
Opened 2021-05-14 12:12 UTC by Asmi-1

2021-05-14 13:22 UTC, Anubhcv approved these changes

2021-05-16 08:46 UTC, Asmi-1 commented
Task-2 completed

2021-05-16 10:02 UTC, Anubhcv requested changes
The url to your task-2 webpage is incorrect, fix it and commit again.

2021-05-16 15:36 UTC, Asmi-1 commented
Web Page Task 2 page url uploaded

2021-05-16 17:20 UTC, Anubhcv approved these changes

2021-05-18 06:47 UTC, merged