webdev task1 completed
EnigmaVSSUT/Induction-2021 pull request #309
Opened 2021-05-14 15:50 UTC by om-parmar

2021-05-14 17:50 UTC, Anubhcv requested changes
The url to your task-2 webpage is incorrect, fix it and commit again.

2021-05-15 13:37 UTC, om-parmar commented
Done,
Would you now please check again

On Fri, 14 May, 2021, 11:21 pm Anubhcv, ***@***.***> wrote:

> *@Anubhcv* requested changes on this pull request.
>
> The url to your task-2 webpage is incorrect, fix it and commit again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EnigmaVSSUT/Induction-2021/pull/309#pullrequestreview-660069448>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT3CAEGCS3A2AYC2MVMLQSTTNVPJHANCNFSM444VEHUQ>
> .
>

2021-05-15 13:44 UTC, om-parmar commented
done,
would you please check again.

2021-05-15 15:12 UTC, Anubhcv approved these changes

2021-05-18 06:48 UTC, merged