TASK 1 AND 2 DONE
EnigmaVSSUT/Induction-2021 pull request #335
Opened 2021-05-15 21:16 UTC by Subhasis-SG

https://subhasis-sg.github.io/web/

2021-05-16 02:11 UTC, chandrasekhar2039 requested changes
Provide the URL of the hosted site as per the Instructions provided.

2021-05-17 06:01 UTC, Subhasis-SG commented
https://subhasis-sg.github.io/web/

2021-05-17 07:25 UTC, Anubhcv requested changes
Add a text file containing the url of your webpage in both the tasks.

2021-05-18 06:35 UTC, Anubhcv approved these changes

2021-05-18 06:49 UTC, merged